#!/usr/bin/env bash
# Rewrites ios/App/App/AppDelegate.swift to lift WKWebView's 60fps render cap.
#
#   ./scripts/patch-ios-highrefresh.sh            # apply the unlock
#   ./scripts/patch-ios-highrefresh.sh --revert   # restore stock Capacitor
#
# WHY A SCRIPT: ios/ is gitignored and fully regenerated (docs/CAPACITOR.md), so
# native edits must live outside it or they vanish on the next `cap add`.
# AppDelegate.swift is ALREADY registered in project.pbxproj, so replacing its
# contents needs no .pbxproj surgery — unlike adding a new source file.
#
# WHAT IT DOES, and the honest limits:
#   1. Flips WebKit's internal PreferPageRenderingUpdatesNear60FPSEnabled to
#      false via the PRIVATE WKPreferences._setEnabled:forFeature:.
#   2. Runs a CADisplayLink at 120Hz calling the PRIVATE
#      WKWebView._updateVisibleContentRects each tick, which is what actually
#      drags the WebContent process into a >60Hz cadence on iOS 26 (Apple
#      disconnected the preference from the compositor there, so #1 alone is
#      inert on current iOS).
#   3. Publishes a natively-measured compositor FPS to window.__compositorFps,
#      because a JS rAF counter CANNOT observe >60 — rAF is itself capped, so
#      the in-page meter reads 60 even when the compositor runs at 120.
#
#   requestAnimationFrame stays capped at 60Hz regardless. This only helps
#   COMPOSITED animations (transform / opacity / filter / clip-path). Anything
#   animating width/height — including the island morph — is layout-bound and
#   unaffected. See docs/CAPACITOR.md → "Animation frame rate".
#
# RISKS, stated plainly:
#   - Two private Apple APIs. App Review may reject. Revert before submitting.
#   - ~10-15% extra battery at sustained 120Hz.
#   - Both calls are guarded by responds(to:) and degrade to a no-op, so a
#     future iOS that removes them loses the unlock rather than crashing.
set -euo pipefail

cd "$(dirname "$0")/.."

APP_DELEGATE="ios/App/App/AppDelegate.swift"
REVERT=0

for arg in "$@"; do
  case "$arg" in
    --revert) REVERT=1 ;;
    *) echo "Unknown argument: $arg" >&2; exit 1 ;;
  esac
done

if [ ! -f "$APP_DELEGATE" ]; then
  echo "Missing $APP_DELEGATE — run 'npx cap add ios' first." >&2
  exit 1
fi

# Shared tail: the Capacitor delegate methods. These are LOAD-BEARING —
# ApplicationDelegateProxy is how kitto:// deep links (email verification, the
# Google OAuth return leg) reach the app. Dropping them silently breaks both.
read -r -d '' CAPACITOR_METHODS <<'SWIFT' || true
    func applicationWillResignActive(_ application: UIApplication) {}

    func applicationWillEnterForeground(_ application: UIApplication) {}

    func applicationWillTerminate(_ application: UIApplication) {}

    func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any] = [:]) -> Bool {
        // Load-bearing: kitto:// deep links (email verification, OAuth return).
        return ApplicationDelegateProxy.shared.application(app, open: url, options: options)
    }

    func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
        // Load-bearing: Universal Links.
        return ApplicationDelegateProxy.shared.application(application, continue: userActivity, restorationHandler: restorationHandler)
    }
SWIFT

if [ "$REVERT" -eq 1 ]; then
  cat > "$APP_DELEGATE" <<SWIFT
import UIKit
import Capacitor

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        return true
    }

    func applicationDidEnterBackground(_ application: UIApplication) {}

    func applicationDidBecomeActive(_ application: UIApplication) {}

${CAPACITOR_METHODS}
}
SWIFT
  echo "Reverted $APP_DELEGATE to stock Capacitor (no private APIs)."
  exit 0
fi

cat > "$APP_DELEGATE" <<SWIFT
import UIKit
import Capacitor
import WebKit

// GENERATED by scripts/patch-ios-highrefresh.sh — do not edit by hand.
// ios/ is regenerated by \`cap add\`/\`cap sync\`; edit the script instead.
//
// Lifts WKWebView's 60fps render cap so COMPOSITED animations (transform /
// opacity / filter / clip-path) can run at ProMotion rates. requestAnimationFrame
// remains capped at 60Hz by Apple's design — that is not fixable from here, so
// layout-driven animation (width/height) sees no benefit.
//
// Uses two PRIVATE Apple APIs. Revert with --revert before App Store submission.

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    private var displayLink: CADisplayLink?
    private weak var webView: WKWebView?
    private var frameCount = 0
    private var windowStart: CFTimeInterval = 0

    // Private selectors, resolved once. Guarded by responds(to:) at call time so
    // an OS that drops them degrades to a no-op instead of trapping.
    private let updateRectsSelector = NSSelectorFromString("_updateVisibleContentRects")

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // The bridge view controller builds its WKWebView during window setup,
        // so this has to wait for the first runloop turn after launch.
        DispatchQueue.main.async { [weak self] in
            self?.enableHighRefreshRate()
        }
        return true
    }

    // MARK: - High refresh rate

    private func enableHighRefreshRate() {
        guard let root = window?.rootViewController?.view,
              let webView = Self.findWebView(in: root) else {
            NSLog("[highrefresh] no WKWebView found — unlock skipped")
            return
        }
        self.webView = webView

        Self.disable60FpsPreference(on: webView)
        startDisplayLink()
    }

    /// Depth-first search for the bridge's web view. Walks the hierarchy rather
    /// than reaching into CAPBridgeViewController so this survives Capacitor
    /// major versions moving their internals around.
    private static func findWebView(in view: UIView) -> WKWebView? {
        if let webView = view as? WKWebView { return webView }
        for subview in view.subviews {
            if let found = findWebView(in: subview) { return found }
        }
        return nil
    }

    /// Flips WebKit's internal PreferPageRenderingUpdatesNear60FPSEnabled off.
    ///
    /// Called through the IMP rather than perform(): the selector takes a
    /// primitive BOOL, and NSObject.perform(_:with:) can only pass objects — a
    /// boxed NSNumber lands as a garbage pointer where a BOOL was expected.
    private static func disable60FpsPreference(on webView: WKWebView) {
        let preferences = webView.configuration.preferences

        let featuresSelector = NSSelectorFromString("_features")
        let setEnabledSelector = NSSelectorFromString("_setEnabled:forFeature:")

        guard preferences.responds(to: featuresSelector),
              preferences.responds(to: setEnabledSelector),
              let features = preferences.perform(featuresSelector)?.takeUnretainedValue() as? [NSObject]
        else {
            NSLog("[highrefresh] WKPreferences._features unavailable — cap not lifted")
            return
        }

        let keySelector = NSSelectorFromString("key")
        typealias SetEnabledForFeature = @convention(c) (AnyObject, Selector, ObjCBool, AnyObject) -> Void

        for feature in features {
            guard feature.responds(to: keySelector),
                  let key = feature.perform(keySelector)?.takeUnretainedValue() as? String,
                  key == "PreferPageRenderingUpdatesNear60FPSEnabled"
            else { continue }

            let imp = preferences.method(for: setEnabledSelector)
            let setEnabled = unsafeBitCast(imp, to: SetEnabledForFeature.self)
            setEnabled(preferences, setEnabledSelector, ObjCBool(false), feature)
            NSLog("[highrefresh] PreferPageRenderingUpdatesNear60FPSEnabled = false")
            return
        }

        NSLog("[highrefresh] preference key not present on this iOS version")
    }

    private func startDisplayLink() {
        stopDisplayLink()
        let link = CADisplayLink(target: self, selector: #selector(step(_:)))
        if #available(iOS 15.0, *) {
            // Requires CADisableMinimumFrameDurationOnPhone in Info.plist
            // (scripts/patch-ios-plist.sh) or iOS clamps this to 60 on iPhone.
            link.preferredFrameRateRange = CAFrameRateRange(minimum: 60, maximum: 120, preferred: 120)
        }
        link.add(to: .main, forMode: .common)
        displayLink = link
        windowStart = CACurrentMediaTime()
        frameCount = 0
    }

    private func stopDisplayLink() {
        displayLink?.invalidate()
        displayLink = nil
    }

    @objc private func step(_ link: CADisplayLink) {
        guard let webView else { return }

        // The actual unlock on iOS 26: nudging the web view each display tick is
        // what pulls the WebContent process onto a >60Hz cadence. The preference
        // above is necessary but, since iOS 26, no longer sufficient alone.
        if webView.responds(to: updateRectsSelector) {
            webView.perform(updateRectsSelector)
        }

        // Publish a NATIVE frame count. A JS rAF counter cannot see past 60
        // because rAF is itself capped, so this is the only way to observe
        // whether the compositor is really running at 120.
        frameCount += 1
        let elapsed = link.timestamp - windowStart
        if elapsed >= 0.5 {
            let fps = Int((Double(frameCount) / elapsed).rounded())
            frameCount = 0
            windowStart = link.timestamp
            webView.evaluateJavaScript("window.__compositorFps=\(fps)", completionHandler: nil)
        }
    }

    // MARK: - Lifecycle

    func applicationDidEnterBackground(_ application: UIApplication) {
        // A 120Hz display link in the background is pure battery burn.
        stopDisplayLink()
    }

    func applicationDidBecomeActive(_ application: UIApplication) {
        if webView != nil && displayLink == nil {
            startDisplayLink()
        }
    }

${CAPACITOR_METHODS}
}
SWIFT

echo "Patched $APP_DELEGATE — WKWebView 60fps cap lift enabled."
echo "Uses PRIVATE Apple APIs. Run with --revert before App Store submission."
