import type { Domain } from '../../../src/models/User'
import type { TaskKind, TaskPriority } from '../../../src/models/Task'

// The recurring spine — the commitments that repeat for three years.
//
// This is what makes the archive read like a life rather than a random bag of
// to-dos. A real household's admin history is mostly the SAME twenty things
// coming round again, and it's that repetition the themes, the duplicate check
// and the "you always pay this late" reading of the data all hang off.

export type Cadence = 'monthly' | 'quarterly' | 'semiannual' | 'annual'

export interface RecurringCommitment {
  id: string
  title: string
  domain: Domain
  cadence: Cadence
  /** Local day of month. Clamped for short months. */
  day: number
  /** Local hour the deadline sits at. */
  hour: number
  /** For non-monthly cadences: the calendar month (1-12) of the first instance. */
  anchorMonth?: number
  priority: TaskPriority
  kind: TaskKind
  /** Minutes, snapped onto ESTIMATE_BUCKETS by the generator. */
  estimate: [number, number]
  issuer?: string
  tags: string[]
  /** EGP range. Rendered into the note so the archive has real texture. */
  amount?: [number, number]
  note?: string
  subtasks?: string[]
}

export const RECURRING: RecurringCommitment[] = [
  // ---- Monthly: the metronome of the archive ----
  {
    id: 'rent',
    title: 'Transfer the rent',
    domain: 'home',
    cadence: 'monthly',
    day: 1,
    hour: 10,
    priority: 'urgent',
    kind: 'reminder',
    estimate: [5, 10],
    issuer: 'Landlord — Mr Sameh',
    tags: ['rent', 'monthly'],
    amount: [11000, 13500],
    note: 'Instapay transfer, same account as last month.',
  },
  {
    id: 'allowance',
    title: 'Send Mum her monthly transfer',
    domain: 'family',
    cadence: 'monthly',
    day: 2,
    hour: 11,
    priority: 'high',
    kind: 'reminder',
    estimate: [5, 10],
    tags: ['family', 'monthly'],
    amount: [3000, 3500],
  },
  {
    id: 'prescription',
    title: 'Refill the monthly prescription',
    domain: 'health',
    cadence: 'monthly',
    day: 3,
    hour: 18,
    priority: 'high',
    kind: 'reminder',
    estimate: [15, 30],
    issuer: 'El Ezaby Pharmacy',
    tags: ['medication', 'monthly'],
    amount: [420, 680],
    note: 'Ask whether the generic is back in stock.',
  },
  {
    id: 'maintenance',
    title: 'Pay the building maintenance fee',
    domain: 'home',
    cadence: 'monthly',
    day: 5,
    hour: 19,
    priority: 'normal',
    kind: 'reminder',
    estimate: [5, 15],
    issuer: 'Building committee',
    tags: ['building', 'monthly'],
    amount: [350, 500],
  },
  {
    id: 'internet',
    title: 'Renew the internet plan',
    domain: 'home',
    cadence: 'monthly',
    day: 8,
    hour: 20,
    priority: 'normal',
    kind: 'reminder',
    estimate: [5, 10],
    issuer: 'WE',
    tags: ['internet', 'monthly'],
    amount: [400, 640],
    note: 'The 200 Mbps package. Renews from the My WE app.',
  },
  {
    id: 'catfood',
    title: 'Buy cat food and litter',
    domain: 'pets',
    cadence: 'monthly',
    day: 10,
    hour: 17,
    priority: 'normal',
    kind: 'reminder',
    estimate: [30, 45],
    tags: ['basbousa', 'monthly'],
    amount: [700, 950],
    note: 'The dry food she actually eats is the salmon one.',
  },
  {
    id: 'electricity',
    title: 'Pay the electricity bill',
    domain: 'finance',
    cadence: 'monthly',
    day: 12,
    hour: 19,
    priority: 'high',
    kind: 'reminder',
    estimate: [5, 15],
    issuer: 'North Cairo Electricity Distribution',
    tags: ['bills', 'utilities'],
    amount: [380, 1250],
    note: 'Meter reading is on the slip under the door.',
  },
  {
    id: 'mobile',
    title: 'Pay the mobile bill',
    domain: 'finance',
    cadence: 'monthly',
    day: 15,
    hour: 21,
    priority: 'normal',
    kind: 'reminder',
    estimate: [5, 10],
    issuer: 'Vodafone Egypt',
    tags: ['bills', 'monthly'],
    amount: [200, 340],
  },
  {
    id: 'water',
    title: 'Pay the water bill',
    domain: 'finance',
    cadence: 'monthly',
    day: 18,
    hour: 19,
    priority: 'normal',
    kind: 'reminder',
    estimate: [5, 15],
    issuer: 'Cairo Water Company',
    tags: ['bills', 'utilities'],
    amount: [90, 210],
  },
  {
    id: 'gas',
    title: 'Pay the gas bill',
    domain: 'finance',
    cadence: 'monthly',
    day: 22,
    hour: 19,
    priority: 'normal',
    kind: 'reminder',
    estimate: [5, 10],
    issuer: 'Town Gas',
    tags: ['bills', 'utilities'],
    amount: [70, 190],
  },
  {
    id: 'creditcard',
    title: 'Settle the credit card statement',
    domain: 'finance',
    cadence: 'monthly',
    day: 25,
    hour: 20,
    priority: 'urgent',
    kind: 'reminder',
    estimate: [10, 15],
    issuer: 'CIB',
    tags: ['bills', 'bank'],
    amount: [2400, 9800],
    note: 'Pay the full statement balance, never the minimum.',
  },
  {
    id: 'savings',
    title: 'Move this month’s savings across',
    domain: 'finance',
    cadence: 'monthly',
    day: 28,
    hour: 12,
    priority: 'normal',
    kind: 'reminder',
    estimate: [5, 15],
    issuer: 'Banque Misr',
    tags: ['savings', 'monthly'],
    amount: [4000, 7000],
  },

  // ---- Quarterly ----
  {
    id: 'vat',
    title: 'File the quarterly tax return',
    domain: 'finance',
    cadence: 'quarterly',
    anchorMonth: 10,
    day: 20,
    hour: 14,
    priority: 'urgent',
    kind: 'reminder',
    estimate: [90, 120],
    tags: ['tax', 'quarterly'],
    note: 'Export the invoices first, then the expenses sheet.',
    subtasks: ['Export the invoices', 'Reconcile expenses', 'Submit on the portal', 'Save the receipt'],
  },
  {
    id: 'waterfilter',
    title: 'Change the water filter cartridges',
    domain: 'home',
    cadence: 'quarterly',
    anchorMonth: 9,
    day: 14,
    hour: 16,
    priority: 'normal',
    kind: 'reminder',
    estimate: [30, 45],
    tags: ['maintenance', 'quarterly'],
    amount: [450, 700],
  },
  {
    id: 'balcony',
    title: 'Deep clean the balcony and storage room',
    domain: 'home',
    cadence: 'quarterly',
    anchorMonth: 8,
    day: 24,
    hour: 10,
    priority: 'low',
    kind: 'list',
    estimate: [120, 180],
    tags: ['cleaning'],
  },
  {
    id: 'tyres',
    title: 'Check tyre pressure and alignment',
    domain: 'car',
    cadence: 'quarterly',
    anchorMonth: 11,
    day: 6,
    hour: 11,
    priority: 'normal',
    kind: 'reminder',
    estimate: [45, 60],
    issuer: 'Bosch Car Service',
    tags: ['car', 'maintenance'],
    amount: [200, 400],
  },
  {
    id: 'schoolfees',
    title: 'Pay the school fees instalment',
    domain: 'family',
    cadence: 'quarterly',
    anchorMonth: 9,
    day: 11,
    hour: 9,
    priority: 'urgent',
    kind: 'reminder',
    estimate: [15, 30],
    issuer: 'Nefertari International School',
    tags: ['school', 'fees'],
    amount: [14000, 19000],
  },
  {
    id: 'deworming',
    title: 'Basbousa’s deworming treatment',
    domain: 'pets',
    cadence: 'quarterly',
    anchorMonth: 8,
    day: 19,
    hour: 18,
    priority: 'normal',
    kind: 'reminder',
    estimate: [15, 30],
    tags: ['basbousa', 'vet'],
  },

  // ---- Twice a year ----
  {
    id: 'acservice',
    title: 'Service the air conditioners',
    domain: 'home',
    cadence: 'semiannual',
    anchorMonth: 9,
    day: 16,
    hour: 11,
    priority: 'normal',
    kind: 'reminder',
    estimate: [90, 120],
    issuer: 'Carrier service centre',
    tags: ['maintenance', 'ac'],
    amount: [800, 1400],
    subtasks: ['Book the technician', 'Clear access to both units', 'Keep the service receipt'],
  },
  {
    id: 'oilchange',
    title: 'Car oil change and full service',
    domain: 'car',
    cadence: 'semiannual',
    anchorMonth: 10,
    day: 9,
    hour: 10,
    priority: 'high',
    kind: 'reminder',
    estimate: [120, 180],
    issuer: 'Ghabbour service centre',
    tags: ['car', 'service'],
    amount: [2200, 3400],
  },
  {
    id: 'dentist',
    title: 'Dentist check-up and cleaning',
    domain: 'health',
    cadence: 'semiannual',
    anchorMonth: 11,
    day: 21,
    hour: 17,
    priority: 'normal',
    kind: 'reminder',
    estimate: [45, 60],
    issuer: 'Dr Nourhan — Smile Studio',
    tags: ['dentist', 'checkup'],
    amount: [600, 900],
  },
  {
    id: 'parentteacher',
    title: 'Parent–teacher meeting',
    domain: 'family',
    cadence: 'semiannual',
    anchorMonth: 12,
    day: 7,
    hour: 15,
    priority: 'high',
    kind: 'reminder',
    estimate: [60, 90],
    issuer: 'Nefertari International School',
    tags: ['school'],
  },
  {
    id: 'vetcheck',
    title: 'Vet check-up for Basbousa',
    domain: 'pets',
    cadence: 'semiannual',
    anchorMonth: 10,
    day: 27,
    hour: 18,
    priority: 'normal',
    kind: 'reminder',
    estimate: [60, 90],
    issuer: 'Maadi Vet Clinic',
    tags: ['basbousa', 'vet'],
    amount: [500, 800],
  },

  // ---- Yearly: the ones with the long lead times ----
  {
    id: 'carlicence',
    title: 'Renew the car licence',
    domain: 'car',
    cadence: 'annual',
    anchorMonth: 11,
    day: 13,
    hour: 9,
    priority: 'urgent',
    kind: 'reminder',
    estimate: [180, 240],
    issuer: 'Traffic Department',
    tags: ['car', 'licence'],
    amount: [1800, 2600],
    subtasks: [
      'Clear any outstanding fines',
      'Get the technical inspection done',
      'Renew the insurance certificate',
      'Go to the traffic unit',
    ],
  },
  {
    id: 'carinsurance',
    title: 'Renew the car insurance',
    domain: 'car',
    cadence: 'annual',
    anchorMonth: 10,
    day: 2,
    hour: 12,
    priority: 'urgent',
    kind: 'reminder',
    estimate: [60, 90],
    issuer: 'Misr Insurance',
    tags: ['car', 'insurance'],
    amount: [6500, 9000],
  },
  {
    id: 'homeinsurance',
    title: 'Renew the home contents insurance',
    domain: 'home',
    cadence: 'annual',
    anchorMonth: 12,
    day: 4,
    hour: 13,
    priority: 'high',
    kind: 'reminder',
    estimate: [45, 60],
    issuer: 'Allianz Egypt',
    tags: ['insurance', 'home'],
    amount: [2200, 3100],
  },
  {
    id: 'bloodwork',
    title: 'Annual blood work panel',
    domain: 'health',
    cadence: 'annual',
    anchorMonth: 9,
    day: 23,
    hour: 8,
    priority: 'high',
    kind: 'reminder',
    estimate: [60, 90],
    issuer: 'Al Mokhtabar labs',
    tags: ['health', 'annual'],
    amount: [900, 1600],
    subtasks: ['Fast from midnight', 'Go before 10am', 'Collect results', 'Send them to Dr Yassin'],
  },
  {
    id: 'eyetest',
    title: 'Book the annual eye test',
    domain: 'health',
    cadence: 'annual',
    anchorMonth: 8,
    day: 29,
    hour: 17,
    priority: 'normal',
    kind: 'reminder',
    estimate: [45, 60],
    issuer: 'Magrabi Eye Centre',
    tags: ['health', 'annual'],
    amount: [500, 800],
  },
  {
    id: 'catvaccine',
    title: 'Basbousa’s annual vaccination booster',
    domain: 'pets',
    cadence: 'annual',
    anchorMonth: 12,
    day: 18,
    hour: 18,
    priority: 'high',
    kind: 'reminder',
    estimate: [45, 60],
    issuer: 'Maadi Vet Clinic',
    tags: ['basbousa', 'vaccination'],
    amount: [600, 900],
  },
  {
    id: 'domain',
    title: 'Renew the domain and hosting',
    domain: 'finance',
    cadence: 'annual',
    anchorMonth: 9,
    day: 8,
    hour: 22,
    priority: 'normal',
    kind: 'reminder',
    estimate: [15, 30],
    issuer: 'Namecheap',
    tags: ['subscription', 'annual'],
    amount: [1200, 1800],
  },
]
